class SkillsStaticData{
   final List<String> skillsData = [
    "Front End Developement",
    "Flutter",
    "React JS",
    "HTML",
    "CSS",
    "Javascript",
    "React Native",
    "Android Developer",
    "Angular JS",
    "IOS Developer",
    "Next.js",
    "Tailwind CSS",
    "SCSS",
    "Developement",
    "NodeJS",
    "MongoDB",
    "Cloud Computing",
    "Python",
    "Wordpress",
    "Data Analysis",
    "Artificial Intelligence",
    "Machine Learning",
    "Java",
    "C++",
    "C",
    "Github",
    "AWS",
    "NoSQL",
    "SQL",
    "Django",
    "C#",
    "php",
    "DevOps",
    "Fashion Design",
    "Graphic Design",
    "Illustrator",
    "Photoshop",
    "Canva",
    "After Effects",
    "Figma",
    "Adobe XD",
    "Webflow",
    "Interaction",
    "Game Design",
    "UI Designing",
    "UX Design",
    "Blender 3d",
    "UI/UX",
    "Maya",
    "CoreIDRAW",
    "Marketing",
    "Content Writing",
    "Social Media Management",
    "Facebook Ads",
    "Google Ads",
    "Copywriting",
    "Influencer Marketing",
    "SEO",
    "Social Media Marketing",
    "Video Editing",
    "Premiere Pro",
    "Final Cut Pro",
    "iMovie",
    "Motion Graphics",
  ];
  final List<String> yourInterests = [
    "AI/ML",
    "Anime",
    "App dev",
    "Art",
    "AR/VR",
    "Atronomy",
    "Blockchain",
    "Coding",
    "Commerce",
    "Competitive Programming",
    "Content creation",
    "Crypto",
    "Cyber security",
    "Dao",
    "English practice",
    "Entrepreneurship",
    "Film/TV",
    "Fitness",
    "Freelancing",
    "Full time jobs",
    "Gaming",
    "Graphic Design",
    "Hackathons",
    "History",
    "Internships",
    "JEE/BITSAT/NEET",
    "Journalism",
    "Law",
    "Marketing",
    "Medical",
    "Memes",
    "Mental Health",
    "Metaverse",
    "Music",
    "NFTs",
    "Personal finance",
    "Philosophy",
    "Photography",
    "Public speaking",
    "Quizzing",
    "Reading",
    "Side hustle",
    " Singing",
    " Sports",
    "Startups",
    "Stock market",
    "Story telling",
    "Tech news",
    "UI/UX",
    "Video editing",
  ];

}